#!/bin/bash
# Precomputation (near + singular setup) throughput sweep for QuadElemList on twisted spheres.
#
# For each (scheme, order, twist, kernel, layer) it builds a cubed-sphere, runs
# BoundaryIntegralOp::Setup() once (warm) and times SetupSingular + SetupNear via SCTL's
# profiler, then reports speed = N_pts / (t_singular + t_near), N_pts = Nelem * order^2.
#
# Self-contained: writes its own driver .cpp, compiles it against this repo's headers, runs,
# and parses the profiler output. Does NOT touch any tracked source or the Makefile.
#
# Usage:
#   ./bench-precomp.sh
# Env overrides:
#   OMP_NUM_THREADS (default 4)   PPF (patches/face, default 3)   TOL (default 1e-9)
#   SCHEMES="Hybrid Adaptive"     ORDERS="8 12"                   OUTDIR (build dir)
set -euo pipefail

WORK_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
: "${OMP_NUM_THREADS:=4}"; export OMP_NUM_THREADS
: "${PPF:=3}"
: "${TOL:=1e-9}"
: "${SCHEMES:=Hybrid Adaptive}"
: "${ORDERS:=8 12}"
: "${OUTDIR:=$(mktemp -d)}"
mkdir -p "$OUTDIR"

# --- SCTL toolchain (gcc/mkl/fftw modules) ---
source "$WORK_DIR/sctl_source"

# --- emit the driver ---
cat > "$OUTDIR/bench-precomp.cpp" <<'CPP'
// Precomp (near+singular setup) throughput sweep. Standalone; generated by bench-precomp.sh.
#include <sctl.hpp>
#include <sctl/experimental/quad_element.hpp>
#include <sctl/experimental/quad_element.cpp>
#include <cstdio>
#include <string>
#include <vector>
using namespace sctl;
#ifndef BP_PPF
#define BP_PPF 3
#endif
#ifndef BP_TOL
#define BP_TOL 1e-9
#endif

template <class Real> void FacePoint(Real& x, Real& y, Real& z, Integer face, Real a, Real b, Real R) {
  switch (face) {
    case 0: x= 1; y= a; z= b; break; case 1: x=-1; y=-a; z= b; break;
    case 2: x= a; y= 1; z=-b; break; case 3: x= a; y=-1; z= b; break;
    case 4: x= a; y= b; z= 1; break; case 5: x=-a; y= b; z=-1; break;
    default: SCTL_ASSERT(false);
  }
  const Real r = sqrt<Real>(x*x+y*y+z*z); x*=R/r; y*=R/r; z*=R/r;
}
template <class Real> QuadElemList<Real> BuildTwistedSphere(Long EO, Long PPF, Real R, Real tw) {
  Vector<Real> X; const Vector<Real>& nds = QuadElemList<Real>::ParamNodes(EO);
  for (Integer f=0; f<6; f++) for (Long iu=0; iu<PPF; iu++) for (Long iv=0; iv<PPF; iv++)
    for (Long i=0;i<EO;i++){ const Real a=2*((iu+nds[i])/(Real)PPF)-1;
      for (Long j=0;j<EO;j++){ const Real b=2*((iv+nds[j])/(Real)PPF)-1; Real x,y,z; FacePoint(x,y,z,f,a,b,R);
        const Real s=sin<Real>(tw*z), c=cos<Real>(tw*z); X.PushBack(x*c+y*s); X.PushBack(-x*s+y*c); X.PushBack(z);} }
  return QuadElemList<Real>(EO, X);
}
template <class Real, class Ker> void run(const char* sch, typename QuadElemList<Real>::QuadScheme scheme, Integer Nbeta,
    const Ker& ker, const char* kn, const char* layer, Long order, Real tw, const char* tn, Long PPF, Real tol, const Comm& comm) {
  QuadElemList<Real> qel = BuildTwistedSphere<Real>(order, PPF, (Real)1, tw);
  qel.SetQuadScheme(scheme, 6, Nbeta, 30);
  BoundaryIntegralOp<Real, Ker> BIOp(ker, false, comm);
  BIOp.SetAccuracy(tol); BIOp.AddElemList(qel);
  const Long Npts = 6*PPF*PPF*order*order;
  BIOp.Setup(); BIOp.ClearSetup();          // warm build-once static caches (exclude first-touch)
  Profile::Enable(true); Profile::reset();
  BIOp.Setup();                              // timed: SetupFarField + SetupSingular + SetupNear
  std::printf("@@CFG scheme=%s order=%ld twist=%s kernel=%s layer=%s Npts=%ld\n", sch, order, tn, kn, layer, Npts);
  Profile::print(&comm, {"t_avg"});
  Profile::reset(); Profile::Enable(false);
}
int main(int argc, char** argv) {
  Comm::MPI_Init(&argc, &argv);
  using Real = double; using QS = QuadElemList<Real>::QuadScheme;
  const Comm comm = Comm::Self();
  const Long PPF = BP_PPF; const Real tol = (Real)BP_TOL; const Integer Nbeta = 200;
  const std::vector<std::pair<const char*,Real>> tws = {{"0",0},{"pi/2",const_pi<Real>()/2},{"pi",const_pi<Real>()}};
  const std::vector<Long> orders = { BP_ORDERS };
  const Laplace3D_FxU lapSL; const Laplace3D_DxU lapDL; const Stokes3D_FxU stkSL; const Stokes3D_DxU stkDL;
  for (const char* schname : { BP_SCHEMES }) {
    const QS scheme = (std::string(schname)=="Hybrid") ? QS::Hybrid : QS::Adaptive;
    for (const Long order : orders) for (const auto& tw : tws) {
      run<Real>(schname, scheme, Nbeta, lapSL, "Lap", "SL", order, tw.second, tw.first, PPF, tol, comm);
      run<Real>(schname, scheme, Nbeta, lapDL, "Lap", "DL", order, tw.second, tw.first, PPF, tol, comm);
      run<Real>(schname, scheme, Nbeta, stkSL, "Stk", "SL", order, tw.second, tw.first, PPF, tol, comm);
      run<Real>(schname, scheme, Nbeta, stkDL, "Stk", "DL", order, tw.second, tw.first, PPF, tol, comm);
    }
  }
  Comm::MPI_Finalize(); return 0;
}
CPP

# BP_ORDERS / BP_SCHEMES as brace-init lists from the env vars.
ORDERS_INIT=$(echo "$ORDERS" | tr ' ' ',')
SCHEMES_INIT=$(printf '"%s",' $SCHEMES); SCHEMES_INIT=${SCHEMES_INIT%,}

echo "# bench-precomp: PPF=$PPF tol=$TOL threads=$OMP_NUM_THREADS schemes=[$SCHEMES] orders=[$ORDERS]"
echo "# compiling..."
g++ -std=c++17 -fopenmp -Wall -Wfloat-conversion -O3 -march=native -DNDEBUG -mno-avx512fp16 \
  -DSCTL_GLOBAL_MEM_BUFF=0 -DSCTL_PROFILE=25 -DSCTL_QUAD_T=__float128 \
  -DBP_PPF="$PPF" -DBP_TOL="$TOL" -DBP_ORDERS="$ORDERS_INIT" -DBP_SCHEMES="$SCHEMES_INIT" \
  -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -DSCTL_HAVE_BLAS -DSCTL_HAVE_LAPACK \
  -lfftw3_omp -DSCTL_FFTW_THREADS -lfftw3 -DSCTL_HAVE_FFTW -lfftw3f -DSCTL_HAVE_FFTWF -lfftw3l -DSCTL_HAVE_FFTWL \
  -I"$WORK_DIR/include" "$OUTDIR/bench-precomp.cpp" -o "$OUTDIR/bench-precomp"

echo "# running..."
"$OUTDIR/bench-precomp" > "$OUTDIR/bench-precomp.out" 2>/dev/null

# --- parse profiler output -> throughput table ---
python3 - "$OUTDIR/bench-precomp.out" <<'PY'
import sys, re
lines = open(sys.argv[1]).read().splitlines()
blocks = []; cur = None
for l in lines:
    if l.startswith('@@CFG'):
        if cur: blocks.append(cur)
        cur = [l]
    elif cur is not None:
        cur.append(l)
if cur: blocks.append(cur)

def val(b, name):
    m = re.search(rf'{name}\s+([\d.]+)', b)
    return float(m.group(1)) if m else float('nan')

hdr = f"{'scheme':8} {'ord':>3} {'twist':>5} {'kern':>4} {'L':>2} {'Npts':>5} {'t_sing':>7} {'t_near':>7} {'t_n+s':>7} {'pts/s':>8}"
cur_key = None
for blk in blocks:
    b = '\n'.join(blk)
    m = dict(re.findall(r'(\w+)=(\S+)', blk[0]))
    sing, near = val(b,'SetupSingular'), val(b,'SetupNear')
    N = int(m['Npts']); t = sing + near
    key = (m['scheme'], int(m['order']))
    if key != cur_key: print("\n"+hdr); cur_key = key
    print(f"{m['scheme']:8} {int(m['order']):3d} {m['twist']:>5} {m['kernel']:>4} {m['layer']:>2} "
          f"{N:5d} {sing:7.3f} {near:7.3f} {t:7.3f} {(N/t if t>0 else 0):8.0f}")
print(f"\n# {len(blocks)} configs. N_pts = Nelem*order^2; speed = N_pts/(t_singular+t_near); times = SCTL t_avg.")
PY

echo "# build/output artifacts in: $OUTDIR"
