name: Codecov

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Compile the project
      - name: Compile
        env:
          CXX: g++-13
          CXXFLAGS: >-
            -std=c++11 -O0 -g -rdynamic -fopenmp -march=native
            -DSCTL_MEMDEBUG -DSCTL_GLOBAL_MEM_BUFF=500 -DSCTL_QUAD_T=__float128
            -DSCTL_PROFILE=5 -DSCTL_VERBOSE -fprofile-arcs -ftest-coverage -lgcov
        run: make -j CXX="$CXX" CXXFLAGS="$CXXFLAGS"

      # Step 3: Run tests
      - name: Run tests
        run: make test

      # Step 4: Upload coverage to Codecov
      - name: Upload coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          bash <(curl -s https://codecov.io/bash) || echo "Codecov upload failed"
